MVCFinalProject/Controllers/ApplyJobController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCFinalProject.Models;

namespace MVCFinalProject.Controllers
{
    public class ApplyJobController : Controller
    {
        JobPortalDBEntities dbobj = new JobPortalDBEntities();
        // GET: ApplyJob
        public ActionResult ApplyJob_Pageload()
        {
            return View();
        }
        public ActionResult Apply_InsertClick(ApplyJobCls clsobj, HttpPostedFileBase file)
        {
            if (file.ContentLength > 0)
            {
                string fname = Path.GetFileName(file.FileName);
                var s = Server.MapPath("~/MVCFOL");
                string pa = Path.Combine(s, fname);
                file.SaveAs(pa);

                var fullpath = Path.Combine("~\\MVCFOL", fname);
                clsobj.resume = fullpath;
            }
            dbobj.sp_applyjob(clsobj.ajobid, clsobj.uid, clsobj.cid, clsobj.resume, clsobj.adt, "Applied");
            clsobj.amsg = "Inserted";
            return View("ApplyJob_Pageload");
        }
    }
}

MVCFinalProject/Controllers/DisplayAllJobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCFinalProject.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace MVCFinalProject.Controllers
{
    public class DisplayAllJobsController : Controller
    {
        JobPortalDBEntities dbobj = new JobPortalDBEntities();
        // GET: DisplayAllJobs
        public ActionResult AllJobs_Pageload()
        {
            return View(GetData());
        }
        private JobSearchCls GetData()
        {
            var joblist = new JobSearchCls();
            List<string> lst = new List<string>();
            var job = dbobj.JobTables.ToList();
            foreach (var e in job)
            {
                var jobcls = new SelectAllJobsCls();
                jobcls.jid = e.Job_Id;
                jobcls.cid = e.Company_Id;
                jobcls.title = e.Job_Title;
                jobcls.description = e.Job_Description;
                jobcls.type = e.Job_Type;
                jobcls.location = e.Job_Location;
                jobcls.skills = e.Job_Skills;
                jobcls.salary = e.Job_Salary;
                jobcls.vacancy = e.Job_Vacancies;
                jobcls.experience = e.Job_Experience;
                jobcls.lastdate = e.Last_Date;
                jobcls.status = e.Job_Status;

                joblist.selectjob.Add(jobcls);
                var s = jobcls.skills;
                lst.Add(s);
                TempData["skl"] = string.Join(" ", lst);
            }
            return joblist;
        }
        public ActionResult SearchJob_Click(JobSearchCls clsobj)
        {
            string qry = "";
            if (!string.IsNullOrWhiteSpace(clsobj.insertjob.experience))
            {
                qry += " and Job_Experience like '%" + clsobj.insertjob.experience + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertjob.skills))
            {
                qry += " and Job_Skills like '%" + clsobj.insertjob.skills + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertjob.location))
            {
                qry += " and Job_Location like '%" + clsobj.insertjob.location + "%'";
            }
            return View("AllJobs_Pageload", getdata1(clsobj, qry));
        }
        private JobSearchCls getdata1(JobSearchCls clsobj, string qry)
        {
            using (var con = new SqlConnection(ConfigurationManager.ConnectionStrings["TestCon"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_jobsearch", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new JobSearchCls();
                while (dr.Read())
                {
                    var jobcls = new SelectAllJobsCls();
                    jobcls.jid = Convert.ToInt32(dr["Job_Id"].ToString());
                    jobcls.cid = Convert.ToInt32(dr["Company_Id"].ToString());
                    jobcls.title = dr["Job_Title"].ToString();
                    jobcls.description = dr["Job_Description"].ToString();
                    jobcls.type = dr["Job_Type"].ToString();
                    jobcls.location = dr["Job_Location"].ToString();
                    jobcls.skills = dr["Job_Skills"].ToString();
                    jobcls.salary = dr["Job_Salary"].ToString();
                    jobcls.vacancy = dr["Job_Vacancies"].ToString();
                    jobcls.experience = dr["Job_Experience"].ToString();
                    jobcls.lastdate = dr["Last_Date"].ToString();
                    jobcls.status = dr["Job_Status"].ToString();
                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }
    }
}

MVCFinalProject/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCFinalProject.Models;

namespace MVCFinalProject.Controllers
{
    public class LoginController : Controller
    {
        JobPortalDBEntities dbobj = new JobPortalDBEntities();
        // GET: Login
        public ActionResult Login_PageLoad()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult AdminHome()
        {
            return View();
        }
        public ActionResult Login_Click(LoginCls clsobj)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(clsobj.username, clsobj.password, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    var uid = dbobj.sp_loginid(clsobj.username, clsobj.password).FirstOrDefault();
                    Session["uid"] = uid;
                    var lgtp = dbobj.sp_logtype(clsobj.username, clsobj.password).FirstOrDefault();
                    if (lgtp == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                    else if (lgtp == "Admin")
                    {
                        return RedirectToAction("AdminHome");
                    }
                }
            }
            else
            {
                ModelState.Clear();
                clsobj.msg = "Invalid Login";
                return View("Login_PageLoad", clsobj);
            }
            return View("Login_PageLoad", clsobj);
        }
    }
}

MVCFinalProject/Views/DisplayAllJobs/AllJobs_Pageload.cshtml
@model MVCFinalProject.Models.JobSearchCls
@{
    ViewBag.Title = "AllJobs_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Display All Jobs</h2>
<div>
    @using (Html.BeginForm("SearchJob_Click", "DisplayAllJobs", FormMethod.Post))
    {
        <table>
            <tr>
                <td style="padding-left:8px;"> <label>Job_Experience:</label></td>
                <td> @Html.TextBoxFor(m => m.insertjob.experience)</td>
                <td style="padding-left:8px;"> <label>Job_Skills:</label></td>
                <td> @Html.TextBoxFor(m => m.insertjob.skills)</td>
                <td style="padding-left:8px;"> <label>Job_Location:</label></td>
                <td> @Html.TextBoxFor(m => m.insertjob.location)</td>
                <td><input type="submit" value="search" /></td>
            </tr>
        </table>
    }
</div>
<div>
    @using (Html.BeginForm("AllJobs_Pageload", "SearchJob", FormMethod.Get))
    {
        if (Model != null)
        {
            if (Model.selectjob != null && Model.selectjob.Count != 0)
            {
                <table class="table">
                    <tr>
                    </tr>
                    <tr>

                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.cid)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.type)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.location)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.skills)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.salary)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.vacancy)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.experience)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.lastdate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertjob.status)
                        </th>
                    </tr>
                    @foreach (var item in Model.selectjob)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.cid)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.location)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.skills)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.salary)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.vacancy)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.experience)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.lastdate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.status)
                            </td>
                            <td>
                                @Html.ActionLink("Apply Now", "ApplyJob_Pageload", "ApplyJob", new { comid = item.cid, jobid = item.jid }, null)
                            </td>
                        </tr>
                    }

                </table>
            }
            else
            {
                <script>
                            alert('no data found');
                </script>
            }
        }
    }
    <div>
        @Html.ActionLink("Back to Home Page", "UserHome", "Login")
    </div>

</div>