MVCFinalProject/Controllers/UserRegController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCFinalProject.Models;

namespace MVCFinalProject.Controllers
{
    public class UserRegController : Controller
    {
        JobPortalDBEntities dbobj = new JobPortalDBEntities();
        // GET: UserReg
        public ActionResult UserInsert_Pageload()
        {
            UserInsertCls user = new UserInsertCls();
            user.MyFavoriteQual = getQualificationData();
            return View(user);

        }
        public List<CheckBoxListHelper> getQualificationData()
        {
            List<CheckBoxListHelper> sts = new List<CheckBoxListHelper>()
            {
                new CheckBoxListHelper{Value="BCA",Text="BCA",IsChecked=false},
                new CheckBoxListHelper{Value="MCA",Text="MCA",IsChecked=false},
                new CheckBoxListHelper{Value="BSC",Text="BSC",IsChecked=false},
                new CheckBoxListHelper{Value="MSC",Text="MSC",IsChecked=false},
                new CheckBoxListHelper{Value="BTECH",Text="BTECH",IsChecked=false},
                new CheckBoxListHelper{Value="MTECH",Text="MTECH",IsChecked=false},
            };
            return sts;
        }
        public ActionResult UserInsert_click(UserInsertCls ClsObj, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/MVCFOL");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\MVCFOL", fname);
                    ClsObj.photo = fullpath;
                }
                var getuid = dbobj.sp_maxid().FirstOrDefault();
                int mid = Convert.ToInt32(getuid);
                int uid = 0;
                if (mid == 0)
                {
                    uid = 1;
                }
                else
                {
                    uid = mid + 1;
                }
                var quid = string.Join(",", ClsObj.SelectedQual);
                ClsObj.qual = quid;
                ClsObj.MyFavoriteQual = getQualificationData();
                dbobj.sp_userinsert(ClsObj.id, ClsObj.name, ClsObj.age, ClsObj.dob, ClsObj.gender, ClsObj.address, ClsObj.email, ClsObj.phone, ClsObj.photo, ClsObj.qual, ClsObj.mark, ClsObj.skill, ClsObj.experience);
                dbobj.sp_logininsert(ClsObj.id, ClsObj.username, ClsObj.password, "User");
                ClsObj.usermsg = "Inserted";
                return View("UserInsert_Pageload", ClsObj);
            }
            return View("UserInsert_Pageload", ClsObj);
        }
    }
}

MVCFinalProject/Views/UserReg/UserInsert_Pageload.cshtml
@model MVCFinalProject.Models.UserInsertCls
@{
    ViewBag.Title = "UserInsert_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Registration</h2>
<div>
    @using (Html.BeginForm("UserInsert_click", "UserReg", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <label>Id:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.id)
        </div>
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div>
            <label>Age:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.age)
            @Html.ValidationMessageFor(m => m.age)
        </div>
        <div>
            <label>Date Of Birth:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.dob)
        </div>
        <div>
            <label>Gender:</label>
        </div>
        <div>
            Male
            @Html.RadioButtonFor(model => model.gender, "Male")
            Female
            @Html.RadioButtonFor(model => model.gender, "Female")
        </div>
        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.address)
        </div>
        <div>
            <label>Email ID:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>Phone:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>
        <div>
            <label>Photo:</label>
        </div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
        </div>
        <div>
            <label>Qualification:</label>
        </div>
        <div>
            @foreach (var item in Model.MyFavoriteQual)
            {
                <label>
                    <input type="checkbox" value="@item.Value" checked="@item.IsChecked" name="selectedQual" id="@item.Value" />@Html.Raw(@item.Text)
                </label>
            }
        </div>
        <div>
            <label>Mark:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.mark)
        </div>
        <div>
            <label>Skills:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.skill)
        </div>
        <div>
            <label>Experience:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.experience)
        </div>
        <div>
            <label>Username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.password)
        </div>
        <div>
            <label>Confirm Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.usermsg)
        </div>

    }
</div>