MVCFinalProject/Controllers/AdminRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCFinalProject.Models;

namespace MVCFinalProject.Controllers
{
    public class AdminRegController : Controller
    {
        JobPortalDBEntities dbobj = new JobPortalDBEntities();
        // GET: AdminReg
        public ActionResult AdminInsert_Pageload()
        {
            return View();
        }
        public ActionResult AdminInsert_Click(AdminInsertCls clsobj)
        {
            if (ModelState.IsValid)
            {
                var getuid = dbobj.sp_maxid().FirstOrDefault();
                int mid = Convert.ToInt32(getuid);
                int uid = 0;
                if (mid == 0)
                {
                    uid = 1;
                }
                else
                {
                    uid = mid + 1;
                }
                dbobj.sp_admininsert(clsobj.id, clsobj.name, clsobj.email, clsobj.phone, clsobj.webaddress);
                dbobj.sp_logininsert(clsobj.id, clsobj.username, clsobj.password, "Admin");
                clsobj.adminmsg = "Inserted";
                return View("AdminInsert_Pageload", clsobj);
            }
            return View("AdminInsert_Pageload", clsobj);
        }
    }
}

MVCFinalProject/Views/AdminReg/AdminInsert_Pageload.cshtml
@model MVCFinalProject.Models.AdminInsertCls
@{
    ViewBag.Title = "AdminInsert_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Registration</h2>
<div>
    @using (Html.BeginForm("AdminInsert_Click", "AdminReg", FormMethod.Post))
    {
        <div>
            <label>Id:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.id)
        </div>
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div>
            <label>Email:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>Phone:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>
        <div>
            <label>Website Address:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.webaddress)
        </div>
        <div>
            <label>Username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.password)
        </div>
        <div>
            <label>Confirm Password:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.adminmsg)
        </div>
    }
</div>